import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { CartProvider } from "./contexts/CartContext";
import { Toaster } from "@/components/ui/toaster"
import NavBar from "../components/clients/navbar";
import Footer from "../components/clients/footer";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <CartProvider>
          <header className="sticky top-0 z-50 bg-grey shadow-md">
            <NavBar></NavBar>
          </header>
          <main className="flex-1">
            {children}
          </main>
          <Toaster />
          <Footer />
        </CartProvider>
      </body>
    </html>
  );
}
